version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: 
        - ./.env.prod
    ports:
    - "5432:5432"
  djangoapp:
    build:
        context: .
        dockerfile: Dockerfile.prod
    command: gunicorn closet.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static:/backend/static
    expose:
      - "8000"
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - ./static:/backend/static
    ports:
      - "80:80"
    depends_on:
      - djangoapp
